#!/bin/bash

RUN_SESSION=20220511
PREFIX="gmm-demo"

GCP_PROJECT="gaussianmixturemodel"

GMM_NUMBER_OF_CLUSTERS=7
ALGORITHM=rdd
DATASET_PATH="/mnt/c/Users/gaspa/IdeaProjects/GMM_Scalability/datasets"
DATASET=1
SEED=2014595

GCS_BUCKET_NAME=${PREFIX}-data-bucket-${RUN_SESSION}
GCS_BUCKET_ZONE=europe-west1
GCS_BUCKET_CLASS=regional

DATAPROC_CLUSTER_NAME=gmm-dataproc-cluster-${RUN_SESSION}
DATAPROC_CLUSTER_REGION=europe-west1
DATAPROC_CLUSTER_ZONE=europe-west1-b
DATAPROC_NUMWORKERS=5
DATAPROC_SCALEDOWN_TO_NUMWORKERS=2